$RNMapboxMapsImpl = 'mapbox'
$RNMapboxMapsVersion = '= 10.17.0'
$RNFirebaseAnalyticsWithoutAdIdSupport=true

pod_folder = Pathname.new(__FILE__).dirname.realpath

require File.join(File.dirname(`cd #{pod_folder} && node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

Pod::UI.puts "Configuring Pod with statically linked Frameworks".green
use_frameworks! :linkage => :static

target 'STSApp' do
  use_expo_modules!
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end

  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

  use_react_native!(
    :path => config[:reactNativePath],
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'STSApp-staging' do
    inherit! :complete
  end

  target 'STSAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    $RNMapboxMaps.post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings["ONLY_ACTIVE_ARCH"] = "NO"
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['VISION_CAMERA_DISABLE_FRAME_PROCESSORS=1', '$(inherited)']
      end
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
    File.delete("./.xcode.env.local") if File.exist?("./.xcode.env.local")
  end
end
